version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-builder
    container_name: authentiqr-backend
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - MONGO_URI=${MONGO_URI}
    env_file:
      - backend/.env
    restart: unless-stopped
    networks:
      - authentiqr-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-builder
    container_name: authentiqr-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5001/api
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - authentiqr-network

networks:
  authentiqr-network:
    driver: bridge

